name: inaxia_catalogue
description: Inaxia Dynamic Catalogue.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+14 # VERSION - WhatsApp Buttons bug fix

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.12
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/whatsapp-logo.jpg
